# Generated by Django 4.1.6 on 2023-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('services', models.CharField(choices=[('Electritian', 'Electritian'), ('Plumber', 'Plumber'), ('Housekeeper', 'Housekeeper'), ('Security guard', 'Security guard'), ('Gardener', 'Gardener'), ('Driver', 'Driver'), ('Nanny /Babysitter', 'Nanny /Babysitter'), ('Pet caretaker', 'Pet caretaker'), ('Mechanic', 'Mechanic'), ('Other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
