# Generated by Django 4.1.6 on 2023-02-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_userregmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuploadmodel',
            name='image',
        ),
    ]
