# Generated by Django 4.1.6 on 2023-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_empuploadmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='useruploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Electritian', 'Electritian'), ('Plumber', 'Plumber'), ('Housekeeper', 'Housekeeper'), ('Security guard', 'Security guard'), ('Gardener', 'Gardener'), ('Driver', 'Driver'), ('Nanny /Babysitter', 'Nanny /Babysitter'), ('Pet caretaker', 'Pet caretaker'), ('Mechanic', 'Mechanic'), ('Other', 'Other')], max_length=20)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
