# Generated by Django 4.1.6 on 2023-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_useruploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='empapplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
