# Generated by Django 4.1.6 on 2023-02-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_empapplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='userapplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
            ],
        ),
    ]
