# Generated by Django 4.1.6 on 2023-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_userwishlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='empwishlistmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('services', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
